behaviors:
  Walker:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    keep_checkpoints: 5
    checkpoint_interval: 5000000
    max_steps: 50000000
    time_horizon: 1000
    summary_freq: 30000
environment_parameters:
  environment_count: 10.0
  walking_direction:
    curriculum:
      - name: Forward # The '-' is important as this is a list
        completion_criteria:
          measure: progress
          behavior: Walker
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.25
        value: 0.0
      - name: Backward # The '-' is important as this is a list
        completion_criteria:
          measure: progress
          behavior: Walker
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.5
        value: 2.0
      - name: Right # The '-' is important as this is a list
        completion_criteria:
          measure: progress
          behavior: Walker
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.75
        value: 1.0
      - name: Left # The '-' is important as this is a list
        completion_criteria:
          measure: progress
          behavior: Walker
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.0
        value: 3.0
